In [253]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from datetime import date
np.set_printoptions(precision=3, suppress=True)
pd.options.mode.use_inf_as_na = True

In [260]:
#Bài 1: Lấy thông tin
housing_data=pd.read_csv('./data/vn_housing_dataset/VN_housing_dataset.csv')
housing_data.info()
housing_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82496 entries, 0 to 82495
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       82496 non-null  int64
 1   Ngày             82496 non-null  object
 2   Địa chỉ          82449 non-null  object
 3   Quận             82495 non-null  object
 4   Huyện            82449 non-null  object
 5   Loại hình nhà ở  82465 non-null  object
 6   Giấy tờ pháp lý  53610 non-null  object
 7   Số tầng          36399 non-null  object
 8   Số phòng ngủ     82458 non-null  object
 9   Diện tích        82495 non-null  object
 10  Dài              19827 non-null  object
 11  Rộng             35445 non-null  object
 12  Giá/m2           82484 non-null  object
dtypes: int64(1), object(12)
memory usage: 8.2+ MB

,Unnamed: 0,Ngày,Địa chỉ,Quận,Huyện,Loại hình nhà ở,Giấy tờ pháp lý,Số tầng,Số phòng ngủ,Diện tích,Dài,Rộng,Giá/m2
0,0,2020-08-05,"Đường Hoàng Quốc Việt, Phường Nghĩa Đô, Quận C...",Quận Cầu Giấy,Phường Nghĩa Đô,"Nhà ngõ, hẻm",Đã có sổ,4,5 phòng,46 m²,NaN,NaN,"86,96 triệu/m²"
1,1,2020-08-05,"Đường Kim Giang, Phường Kim Giang, Quận Thanh ...",Quận Thanh Xuân,Phường Kim Giang,"Nhà mặt phố, mặt tiền",NaN,NaN,3 phòng,37 m²,NaN,NaN,"116,22 triệu/m²"
2,2,2020-08-05,"phố minh khai, Phường Minh Khai, Quận Hai Bà T...",Quận Hai Bà Trưng,Phường Minh Khai,"Nhà ngõ, hẻm",Đã có sổ,4,4 phòng,40 m²,10 m,4 m,65 triệu/m²
3,3,2020-08-05,"Đường Võng Thị, Phường Thụy Khuê, Quận Tây Hồ,...",Quận Tây Hồ,Phường Thụy Khuê,"Nhà ngõ, hẻm",Đã có sổ,NaN,6 phòng,51 m²,12.75 m,4 m,100 triệu/m²
4,4,2020-08-05,"Đường Kim Giang, Phường Kim Giang, Quận Thanh ...",Quận Thanh Xuân,Phường Kim Giang,"Nhà ngõ, hẻm",NaN,NaN,4 phòng,36 m²,9 m,4 m,"86,11 triệu/m²"

In [284]:
 house_price=housing_data[['Diện tích','Dài','Rộng','Giá/m2']]
#date['Ngày']=housing_data[['Ngày']]                   
#house_date=house_price.join(date)

house_price

      Diện tích      Dài Rộng           Giá/m2
0         46 m²      NaN  NaN   86,96 triệu/m²
1         37 m²      NaN  NaN  116,22 triệu/m²
2         40 m²     10 m  4 m      65 triệu/m²
3         51 m²  12.75 m  4 m     100 triệu/m²
4         36 m²      9 m  4 m   86,11 triệu/m²
...         ...      ...  ...              ...
82491     38 m²      NaN  NaN   81,58 triệu/m²
82492     50 m²      NaN  NaN     292 triệu/m²
82493     41 m²      NaN  NaN  341,46 triệu/m²
82494     60 m²      NaN  NaN  101,67 triệu/m²
82495     45 m²      NaN  NaN  102,22 triệu/m²

[82496 rows x 4 columns]

In [285]:
# Bài 2: Kiểm tra các thông tin bất thường
house_price.isna().sum()

Diện tích        1
Dài          62669
Rộng         47051
Giá/m2          12
dtype: int64

In [426]:
#loại bỏ các thông tin bất thường ở các cột
drop_nan=house_price.dropna(axis = 0, how = "any")
drop_nan

       index Diện tích      Dài   Rộng           Giá/m2
0          2     40 m²     10 m    4 m      65 triệu/m²
1          3     51 m²  12.75 m    4 m     100 triệu/m²
2          4     36 m²      9 m    4 m   86,11 triệu/m²
3          5     46 m²   12.1 m  3.8 m  104,35 triệu/m²
4          8     75 m²     12 m  6.5 m     120 triệu/m²
...      ...       ...      ...    ...              ...
19696  82355     37 m²     13 m    3 m   43,24 triệu/m²
19697  82356    100 m²     16 m    6 m     115 triệu/m²
19698  82359     80 m²     14 m    5 m   262,5 triệu/m²
19699  82361     89 m²     20 m    4 m  258,43 triệu/m²
19700  82362     90 m²     20 m    4 m   64,44 triệu/m²

[19701 rows x 5 columns]

In [427]:
#Kiểm tra lại xem đã xoá hết các giá trị NAn ở chưa
drop_nan.isna().any()

index        False
Diện tích    False
Dài          False
Rộng         False
Giá/m2       False
dtype: bool

In [429]:
#format ngày
date=housing_data[['Ngày']]   
print('Ngày trước khi đổi:\n',date)
datenew=date['Ngày'].str.replace('-','_')
print('Ngày sau khi đổi:\n',datenew)

Ngày trước khi đổi:
              Ngày
0      2020-08-05
1      2020-08-05
2      2020-08-05
3      2020-08-05
4      2020-08-05
...           ...
82491  2019-08-23
82492  2019-08-07
82493  2019-08-07
82494  2019-08-05
82495  2019-08-05

[82496 rows x 1 columns]
Ngày sau khi đổi:
 0        2020_08_05
1        2020_08_05
2        2020_08_05
3        2020_08_05
4        2020_08_05
            ...
82491    2019_08_23
82492    2019_08_07
82493    2019_08_07
82494    2019_08_05
82495    2019_08_05
Name: Ngày, Length: 82496, dtype: object

In [430]:
#format giá nhà
price=housing_data["Giá/m2"]
for value in price:
    if 'tỷ' in str(value):
        ty_to_trieu=value.replace('tỷ', 'triệu')
        print(ty_to_trieu)
pricenew=drop_nan['Giá/m2'].str.replace('tỷ', 'triệu')
print("Giá sau khi đổi: \n", pricenew)

1,202777777 triệu/m²
1,142857142 triệu/m²
1,96 triệu/m²
1,557142857 triệu/m²
1,316666666 triệu/m²
1,2 triệu/m²
1,111111111 triệu/m²
1,8 triệu/m²
2,2 triệu/m²
2,28 triệu/m²
1,166666666 triệu/m²
1,324324324 triệu/m²
1,297297297 triệu/m²
1,06 triệu/m²
3,536585365 triệu/m²
1,133333333 triệu/m²
2,1001 triệu/m²
1 triệu/m²
2,65 triệu/m²
1,153846153 triệu/m²
1,594405594 triệu/m²
1,597222222 triệu/m²
11,5 triệu/m²
10,416666666 triệu/m²
6,5 triệu/m²
1 triệu/m²
1,446153846 triệu/m²
8,333333333 triệu/m²
7,894736842 triệu/m²
1,114285714 triệu/m²
1,008333333 triệu/m²
6,833333333 triệu/m²
1,023809523 triệu/m²
1,586206896 triệu/m²
1,52 triệu/m²
124 triệu/m²
52,5 triệu/m²
1,3 triệu/m²
16,7 triệu/m²
1,14 triệu/m²
8,9 triệu/m²
1,2875 triệu/m²
1,25 triệu/m²
1,076923076 triệu/m²
1,777777777 triệu/m²
1,79245283 triệu/m²
1,083333333 triệu/m²
3,898305084 triệu/m²
1,125 triệu/m²
6,666666666 triệu/m²
1,033333333 triệu/m²
1,063829787 triệu/m²
1,26 triệu/m²
70,70694445 triệu/m²
1,05 triệu/m²
6,666666666 triệu/m²
1,688888888 triệu/m²
1,333333333 triệu/m²
1,55 triệu/m²
1,09375 triệu/m²
66,666666666 triệu/m²
8 triệu/m²
8,571428571 triệu/m²
9,375 triệu/m²
1,09375 triệu/m²
9,516129032 triệu/m²
1,033333333 triệu/m²
1,362068965 triệu/m²
112,697142857 triệu/m²
1,11111 triệu/m²
5,666666666 triệu/m²
1,419354838 triệu/m²
1 triệu/m²
7,5 triệu/m²
2,0625 triệu/m²
2,888888888 triệu/m²
88,96 triệu/m²
1 triệu/m²
2.222,22220022 triệu/m²
1,083333333 triệu/m²
1,05 triệu/m²
1,46 triệu/m²
1,122448979 triệu/m²
6,93877551 triệu/m²
1,076923076 triệu/m²
1,04 triệu/m²
1,066666666 triệu/m²
728.000,00728 triệu/m²
69.736,842105263 triệu/m²
1,514285714 triệu/m²
1,525 triệu/m²
1 triệu/m²
1,875 triệu/m²
1 triệu/m²
6,666666666 triệu/m²
1,409090909 triệu/m²
2,346938775 triệu/m²
1,75 triệu/m²
1,0625 triệu/m²
1,125 triệu/m²
1,083333333 triệu/m²
1,041666666 triệu/m²
1,04 triệu/m²
9,833333333 triệu/m²
5,375 triệu/m²
1,925 triệu/m²
1,625 triệu/m²
7,692307692 triệu/m²
1,033333333 triệu/m²
1,4 triệu/m²
1,25 triệu/m²
1,117647058 triệu/m²
10 triệu/m²
5,833333333 triệu/m²
1,0125 triệu/m²
1,706666666 triệu/m²
1,5 triệu/m²
2,538461538 triệu/m²
Giá sau khi đổi:
 0            65 triệu/m²
1           100 triệu/m²
2         86,11 triệu/m²
3        104,35 triệu/m²
4           120 triệu/m²
              ...
19696     43,24 triệu/m²
19697       115 triệu/m²
19698     262,5 triệu/m²
19699    258,43 triệu/m²
19700     64,44 triệu/m²
Name: Giá/m2, Length: 19701, dtype: object

In [448]:
sum = pd.concat((drop_nan.drop('Giá/m2',axis=1), pricenew, datenew),axis=1)
sum.dropna(axis =0, how ='any').to_csv('bài tập tuần 5.csv', index=False)